apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grocery
  template:
    metadata:
      labels:
        app: grocery
    spec:
      containers:
      - name: grocery-container
        image: nginx:1.25
