apiVersion: apps/v1
kind: Deployment
metadata:
  name: Grocery-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Grocery
  template:
    metadata:
      labels:
        app: Grocery
    spec:
      containers:
      - name: Grocery-container
        image: nginx:1.25
